### ISSUE TITLE
USER STORY: <Collect feedback with polls> 

### ISSUE THREAD

**Issue by KeepKindling** [KeepKindling/my-first-agile-project#13]
In order to **collect feedback on certain topics** as an **administrator**, I can **publish polls for users to vote on**.

## Acceptance Criteria:

- Acceptance criteria 1: **I have the choice for adding or removing as many options as I want to the poll**.
- Acceptance criteria 2: **I can add a title for the poll before publishing**.
- Acceptance criteria 3: **I can choose to show a brief description of the poll's goals as an about section**.
- Acceptance criteria 4: **I can have more than one poll active if I so choose**.

## Tasks

- [ ] Create add and remove buttons to decide how many options the poll will have.
- [ ] Develop HTML and CSS for title and about section.
- [ ] Develop the relative relationship between the screen size and the options boxes.
- [ ] Use HTML and CSS to allow administrator to create more than one active poll
- [ ] Design the aesthetics for the poll to fit in naturally with the website
